export const products = [
  {
    id: '1',
    name: 'Product 1',
    price: 24970,
    briefInfo: 'Product 1 brief info',
    fullInfo: 'Product 1 full information',
    image: 'http://localhost:3000/product.jpg',
  },
  {
    id: '2',
    name: 'Product 2',
    price: 34354,
    briefInfo: 'Product 2 brief info',
    fullInfo: 'Product 2 full information',
    image: 'http://localhost:3000/product.jpg',
  },
  {
    id: '3',
    name: 'Product 3',
    price: 4354546,
    briefInfo: 'Product 3 brief info',
    fullInfo: 'Product 3 full information',
    image: 'http://localhost:3000/product.jpg',
  },
  {
    id: '4',
    name: 'Product 4',
    price: 3565676,
    briefInfo: 'Product 4 brief info',
    fullInfo: 'Product 4 full information',
    image: 'http://localhost:3000/product.jpg',
  },
  {
    id: '5',
    name: 'Product 5',
    price: 76848,
    briefInfo: 'Product 5 brief info',
    fullInfo: 'Product 5 full information',
    image: 'http://localhost:3000/product.jpg',
  },
  {
    id: '6',
    name: 'Product 6',
    price: 768295,
    briefInfo: 'Product 6 brief info',
    fullInfo: 'Product 6 full information',
    image: 'http://localhost:3000/product.jpg',
  },
  {
    id: '7',
    name: 'Product 7',
    price: 5473,
    briefInfo: 'Product 7 brief info',
    fullInfo: 'Product 7 full information',
    image: 'http://localhost:3000/product.jpg',
  },
  {
    id: '8',
    name: 'Product 8',
    price: 7364,
    briefInfo: 'Product 8 brief info',
    fullInfo: 'Product 8 full information',
    image: 'http://localhost:3000/product.jpg',
  },
  {
    id: '9',
    name: 'Product 9',
    price: 1243987,
    briefInfo: 'Product 9 brief info',
    fullInfo: 'Product 9 full information',
    image: 'http://localhost:3000/product.jpg',
  },
];
